##
## EPITECH PROJECT, 2018
## cpp_arcade
## File description:
## Created by sahel.lucas-saoudi@epitech.eu,
##

all:
		make -C Nibbler

clean:
		make -C Nibbler clean

fclean:
		make -C Nibbler fclean

re:
		make -C Nibbler re

.PHONY: all clean fclean re
