##
## EPITECH PROJECT, 2018
## cpp_arcade
## File description:
## Created by sahel.lucas-saoudi@epitech.eu,
##

all:
		make -C Nibbler
		make -C Qix

clean:
		make -C Nibbler clean
		make -C Qix clean

fclean:
		make -C Nibbler fclean
		make -C Qix fclean

re:
		make -C Nibbler re
		make -C Qix re

debug:
		make -C Nibbler debug
		make -C Qix debug

.PHONY: all clean fclean re debug
