##
## EPITECH PROJECT, 2018
## cpp_arcade
## File description:
## Created by sahel.lucas-saoudi@epitech.eu,
##

all:
		make -C SFML
		make -C NCurses

clean:
		make -C SFML clean
		make -C NCurses clean
        
fclean:
		make -C SFML fclean
		make -C NCurses fclean

re:
		make -C SFML re
		make -C NCurses re

.PHONY: all clean fclean re
